// <auto-generated />
using System;
using EfCoreValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreValueObjects.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20220113132954_TPHForOwnedTypes")]
    partial class TPHForOwnedTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EfCoreValueObjects.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EfCoreValueObjects.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator<int>("Type");
                });

            modelBuilder.Entity("EfCoreValueObjects.Employee", b =>
                {
                    b.HasBaseType("EfCoreValueObjects.Person");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("EfCoreValueObjects.Student", b =>
                {
                    b.HasBaseType("EfCoreValueObjects.Person");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("EfCoreValueObjects.Company", b =>
                {
                    b.OwnsMany("EfCoreValueObjects.CompanyAddress", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("AddressLine1")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("CompanyId", "City", "AddressLine1", "Type");

                            b1.ToTable("CompanyAddress");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
